menu:
 # Home: /
  Archives: /archives
  Reading: /reading
  About: /about
#rss: /atom.xml
rss: 

excerpt_link: Read More
archive_yearly: false
archive_date_format: MMM DD
fancybox: true

widgets:
	- category
	- tagcloud
	- recent_posts

duoshuo_shortname:

google_analytics:
favicon: /favicon.ico
